Статистика: лучшее событие
MindboxDevSchool/TryScrumTeam pull request #89
Opened 2020-11-02 18:46 UTC by FokusHuk

2020-11-02 18:47 UTC, FokusHuk commented
Пока что без приоритетов. Я не успел. Не уверен, что там нужен exception, писал его еще до обзора и планирования. В общем, посмотрите, там все не очень идеально. Но правки после ревью смогу внести только завтра вечером. Так что, если хотите продолжить писать дальше сервис статистик, то исправьте сами (ну или замерджите и добавьте таски).

2020-11-02 20:14 UTC, moskovets requested changes
Мы определили, что сервис статистики имеет два метода - получить общую статистику для пользователя, и получить статистику для отслеживания пользователя. Сервис возвращает набор строк, с фактами статистик.

В методе статистики отслеживания нам нужно один раз загрузить события из репозитория, а потом уже передать их в каждую статистику и посчитать результат. Я бы предложила написать для каждой статистики свой класс с методами проверки применимости, собственно применения, своими настройками. Тогда можно будет писать тесты не на сервис статистики, а на каждую статистику. Причем, отдельно тестировать функцию применимости и применения. Статистику худшее/лучшее можно объединить в один класс, так как у них одинаковая логика.

И исключения не нужны

2020-11-02 20:14 UTC, moskovets commented on ItHappened/appsettings.json
> +}
Структурировать json лучше по каждой статистике, т.е для поля SearchingBestEvent указать 3 настраиваемых поля и т.д.

2020-11-02 20:14 UTC, moskovets commented on ItHappened/ItHappenedSettings.cs
> +        {
Этот конструктор станет гигантским для всех статистик. Возможно, следует хранить словарь настроек для каждой статистики.

2020-11-02 20:14 UTC, moskovets commented on ItHappened/Application/StatisticsService.cs
> +            return new EventDto(bestEvent);
статистика возвращает не объект, а строку с текстом. Или, в более общем случае - объект статистики с текстом, данными для иллюстрации и приоритетом

2020-11-02 20:14 UTC, moskovets commented on ItHappened/Application/StatisticsService.cs
> +                    trackEventsWithRating
не понимаю, зачем работать с trackEventsWithRating, если можно просто взять первый из отсортированного по дате списка событий. 

сейчас написано так, что пропустив 9 ближайших событий мы не получим раннюю дату. Если события с рейтингом будут происходить несколько раз в день, например на протяжении 6 месяцев, то это удовлетворит условие, но код не сработает. 

> самое раннее событие было раньше, чем 3 месяца назад,

```suggestion
                    trackEvents..OrderBy(@event => @event.CreatedAt).First().CreatedAt
```

2020-11-02 20:14 UTC, moskovets commented on ItHappened/Application/StatisticsService.cs
> +                        .CreatedAt,
думаю, пользователя интересует ближайшее из лучших событий.

2020-11-04 17:15 UTC, FokusHuk commented
Все, что было на ревью исправил. Настройки поменял, exception-ы удалил. Факты статистики будут в отдельных классах. Ну и контроллер тоже добавил, можете чекнуть

2020-11-04 19:02 UTC, moskovets requested changes
Не понимаю необходимости в тесте сервиса статистик - его неудобно расширять, он начнет падать при добавлении новых фактов, он не является юнит тестом - потому что иначе нужно мокать классы фактов.
Либо можно написать один тест где замокать классы фактов - проверить что все работает и создается нужный список статистик. 

Очень понравился сам сервис статистик, интерфейсы для фактов - прям офигенно выглядит!

2020-11-04 19:02 UTC, moskovets commented on ItHappend.RestAPI/Controllers/StatisticsController.cs
> +        [Route("track={trackId}")]
странный роут. Предложила бы повесить статистику на трек 
tracks/id/statistics
а общую - просто на statistics

2020-11-04 19:02 UTC, moskovets commented on ItHappened/Domain/StatisticsFacts/BestEventFact.cs
> +                       DateTime.Now - TimeSpan.FromDays(_settings.BestEvent.DaysSinceLastEvent)) < 0 &&
> только если количество событий с рейтингом в отслеживании больше 10, самое раннее событие было раньше, чем 3 месяца назад, а событие с минимальным рейтингом было больше недели назад.

во 2-м условии самое раннее событие - среди всех, т.е нужно учитывать события без рейтинга. 
Это можно у ПО уточнить.

2020-11-04 19:02 UTC, moskovets commented on ItHappend.Tests/StatisticsFactsTests/BestEventFactTests.cs
> +        public void Process_DaysSinceBestEventIsNotCorrect_ReturnNotApplicableFact()
DaysSinceBestEventIsNotCorrect
не совсем  корректные названия тестов. Количество дней корректно. А тест описывает случай, что нет событий, которые не походят под условие DaysSinceBestEvent

2020-11-04 20:59 UTC, AndrewGronin approved these changes
Здорово, единственное что не понравилось - названия полей конфига ,если до смысла DaysSinceLastEvent и DaysSinceBestEvent еще можно догадатся, то EventsWithRatingCount как то совсем мимо, понятнее было бы что вроде MinimalAmountOfEventsWithRatingToApply.

2020-11-04 20:59 UTC, AndrewGronin commented on ItHappend.Tests/ServiceTests/StatisticsServiceTests.cs
> +                .Returns(events);
тоже что в других тестах, гуид любой,а ответ конкретный, нужно конкретный гуид принимать

2020-11-04 22:36 UTC, FokusHuk commented on ItHappend.Tests/ServiceTests/StatisticsServiceTests.cs
> +                .Returns(events);
Окей, пересмотрю тесты и название настройки

2020-11-04 22:39 UTC, FokusHuk commented on ItHappend.Tests/StatisticsFactsTests/BestEventFactTests.cs
> +        public void Process_DaysSinceBestEventIsNotCorrect_ReturnNotApplicableFact()
Ну это, смотря как рассматривать понятие "корректно", можно конечно DaysSinceBestEventIsNotSatisfyRequiredCondition, ну или предложи еще вариант

2020-11-04 22:40 UTC, FokusHuk commented on ItHappened/Domain/StatisticsFacts/BestEventFact.cs
> +                       DateTime.Now - TimeSpan.FromDays(_settings.BestEvent.DaysSinceLastEvent)) < 0 &&
Ну да, я думаю лучше уточнить, завтра спрошу, потому что вообще рассматриваются события с рейтингом, так что спорный момент

2020-11-05 08:57 UTC, merged